"""empty message

Revision ID: a0ba09c7a720
Revises: 
Create Date: 2022-05-07 08:51:46.131195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ba09c7a720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'positions', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'restaurant_id')
    # ### end Alembic commands ###
